Added base tests for BaseWatchFunction - RI.

diff --git a/CI/run_tests b/CI/run_tests
--- a/CI/run_tests
+++ b/CI/run_tests
@@ -31,7 +31,11 @@ do
 	fi
 done
 echo "-------------------------------------------------------------------------"
-echo "All tests run. $FAILEDCOUNT Failed Tests ( $FAILEDTESTS)"
-
+if [ $FAILEDCOUNT -gt 0 ]; then
+	echo "$FAILEDCOUNT Tests Failed ( $FAILEDTESTS)"
+	exit 1
+else
+	echo "All tests Passed"
+fi
 exit 0
 
